[manifest]
version = "1.0.0"
priority = 15

[[patches]]
[patches.pattern]
target = '=[SMODS _ "src/utils.lua"]'
pattern = "-- TARGET: add your own CardAreas for joker evaluation"
position = "before"
match_indent = true
payload = "table.insert(t, 1, G.weapons)"

[[patches]]
[patches.pattern]
target = '=[SMODS _ "src/utils.lua"]'
pattern = "-- TARGET: add your own CardAreas for joker evaluation"
position = "before"
match_indent = true
payload = "t[#t+1] = G.debuffs"

[[patches]]
[patches.pattern]
target = '=[SMODS _ "src/utils.lua"]'
pattern = "if area and #G[area].cards < G[area].config.card_limit + edition_card_limit then"
position = "at"
match_indent = true
payload = "if area and (#G[area].cards < G[area].config.card_limit + edition_card_limit) or G[area] == G.weapons then"

[[patches]]
[patches.pattern]
target = 'game.lua'
pattern = '''
self.mxms_horoscope_W,
self.mxms_horoscope_H,
'''
position = "at"
match_indent = true
payload = '''
self.mxms_horoscope_W * 0.5,
self.mxms_horoscope_H * 0.5,
'''

# Emplace weapons in their own area
[[patches]]
[patches.pattern]
target = "functions/button_callbacks.lua"
pattern = '''
elseif card.ability.set == 'Booster' then
'''
position = "before"
payload = '''
elseif card.ability.set == 'Weapon' then
    card:add_to_deck()
    G.weapons:emplace(card)
    play_sound('card1', 0.8, 0.6)
    play_sound('generic1')
    dont_dissolve = true
    delay_fac = 0.2
'''
match_indent = true

# Emplace debuffs in their own area
[[patches]]
[patches.pattern]
target = "functions/button_callbacks.lua"
pattern = '''
elseif card.ability.set == 'Booster' then
'''
position = "before"
payload = '''
elseif card.ability.set == 'Debuff' then
    card:add_to_deck()
    G.debuffs:emplace(card)
    play_sound('card1', 0.8, 0.6)
    play_sound('generic1')
    dont_dissolve = true
    delay_fac = 0.2
'''
match_indent = true

# Add Pool and Global Object
[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = '''if (v.type == 'Base' or v.type == 'Enhanced') and G.GAME.used_vouchers["v_illusion"] and pseudorandom(pseudoseed('illusion')) > 0.8 then '''
position = "before"
payload = '''
-- For Abyssal deck
SMODS.calculate_context({modify_shop_joker = true, card = card})
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "globals.lua"
pattern = '''
RENTAL = HEX('b18f43'),
'''
position = "after"
payload = '''
FVB_PR = HEX("2A2051"),
FVB_SC = HEX("E0569B"),
'''
match_indent = true
times = 1