--- assert(SMODS.load_file('jokers/buffs.lua'))()
assert(SMODS.load_file('mechanics/weaponslot.lua'))()
assert(SMODS.load_file('consumables/weapons.lua'))()
assert(SMODS.load_file('consumables/packs.lua'))()
assert(SMODS.load_file('consumables/buffs.lua'))()
assert(SMODS.load_file('util/overrides.lua'))()
assert(SMODS.load_file('jokers/personality.lua'))()
assert(SMODS.load_file('mechanics/backs.lua'))()