SMODS.Atlas({key = "othercards", px = 71, py = 95, path = "othercards.png"})
SMODS.Atlas({key = "basicpack", px = 71, py = 95, path = "basicpack.png"})
SMODS.Atlas({key = "goldpack", px = 71, py = 95, path = "goldpack.png"})
SMODS.Atlas({key = "weapons", px = 71, py = 95, path = "Weapons.png"})
SMODS.Atlas({key = "boira", px = 71, py = 95, path = "Boira.png"})
SMODS.Atlas({key = "personalities", px = 71, py = 95, path = "personalities.png"})
SMODS.Atlas({key = "card_backs", px = 71, py = 95, path = "backs_sheet.png"})
SMODS.Atlas({key = "poisoned", px = 71, py = 95, path = "poisoned.png"})
SMODS.Atlas({key = "fortune_deck", px = 71, py = 95, path = "fortune_back.png"})
SMODS.Atlas({key = "voucher", px = 71, py = 95, path = "vouchers.png"})
SMODS.Atlas({key = "jam", px = 34, py = 34, path = "the_jam.png", atlas_table = "ANIMATION_ATLAS", frames = 21})